version: '3'
services:
  wordpress:
    container_name: wordpress
    image: "wordpress"
    ports:
     - "8080:80"
    environment:
      WORDPRESS_DB_PASSWORD: MyP@sw0rd
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
    restart: always
    networks:
      - jay_bridge
    depends_on:
      - mysql


  mysql:
    container_name: jaymysql
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: MyP@sw0rd
      MYSQL_ROOT_PASSWORD: MyP@sw0rd
    restart: always
    networks:
      - jay_bridge


networks:
  jay_bridge:
